google = "http://www.google.com"
metacritic_URL = "https://www.metacritic.com/"
metacritic_google_page = "//h3[contains(text(),'Metacritic - Movie Reviews, TV Reviews, Game Revie')]"
games_button = "//nav[@id='primary_nav_item_games']"
signUp = "signup"
login_email_field = "login_email"
login_password_field = "login_password"
login_button = "login"
logout_button = "//a[contains(text(),'Logout')]"
metacritic_search = "primary_search_box"
alan_wake_PC = '//*[@href="/game/pc/alan-wake"]'
write_a_review_button = "//span[contains(text(),'Write a Review')]"
review_field = "review_body"
correct_review = "Alan Wake. Just the name alone gives off creepy, supernatural and literary vibes."
submit_review_button = "//input[@name='post-review']"
account_email = "r1995pley@gmail.com"
account_password = "Intothewild1995"
registration_button = "account_signup"
user_name_field = "userName"
incorrect_user_name = "--$!karlpolonks"
registration_email_field = "signup_email"
different_email = "alaska1995@gmail.com"
registration_email_field_confirm = "signup_email_confirm"
registration_password = "signup_password"
register_button = "visRegister"
incorrect_email = "r1995pley@gmailcom"
incorrect_review = "Alan Wake. Just the name alone gives off creepy, supernatural and literary"
